sudo:          false
language:      node_js
node_js:
  - "node"
install:       npm install
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules
deploy: 
  provider: heroku
  api_key:
    secure: 0b89056e-59b7-461f-84cd-52d983dc7338

